image: gitpod/workspace-full-vnc
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
tasks:
  - before: sdk install java 17.0.4.1-tem
 # - init: pip3 install -r requirements.txt
    # command: python3 main.py
    # run: |
    #   pyenv version 3.10.9
    #   pyenv local 3.10.9
